Added pre-commit hook checking spotless

diff --git a/report-viewer/.husky/pre-commit b/report-viewer/.husky/pre-commit
--- a/report-viewer/.husky/pre-commit
+++ b/report-viewer/.husky/pre-commit
@@ -1,2 +1,20 @@
 cd ./report-viewer
 npx lint-staged
+
+
+#spotless
+
+#prevents the shell from aborting if maven returns a non zero exit code
+set +e
+echo Checking spotless
+cd ..
+mvn spotless:check &> /dev/null
+exitCode=$?
+
+echo $exitCode
+
+if [ $exitCode -gt 0 ]
+then
+	echo "Spotless failed. Please run 'mvn spotless:apply' to fix."
+fi
+exit $exitCode
